### ISSUE TITLE
[Question] 08: URL 단축 설계 잠재적인 보안 결함

### ISSUE THREAD

**Issue by semi-cloud** [Read-Book-Together/2023-system-design-interview#10]
### p138
+ 그림 8-8에서 많은 트래픽의 URL 단축 요청이 들어왔을때 이미 웹 서버와 DB도 여러대 두고 있는데, 어느 부분에서 잠재적인 "보안" 결함을 가지고 있다는 것인가?

**Comment by gunh0** [comment]
https://www.boannews.com/media/view.asp?idx=104743
