### ISSUE TITLE
[Week02] 1&4장 문제 바로가기

### ISSUE THREAD

**Issue by semi-cloud** [Read-Book-Together/2023-system-design-interview#3]
### 1장(추가)
+ [데이터베이스](https://github.com/Read-Book-Together/2023-system-design-interview/blob/semi-week02/1장%20사용자%20수에%20따른%20규모%20확장성/데이터베이스.md)
  + 문제 2개
+ [메시지 큐](https://github.com/Read-Book-Together/2023-system-design-interview/blob/semi-week02/1장%20사용자%20수에%20따른%20규모%20확장성/메시지%20큐.md)
  + 문제 1개

### 4장
+ [처리율 제한 알고리즘 상세 설계](https://github.com/Read-Book-Together/2023-system-design-interview/blob/semi-week02/4장%20처리율%20제한%20장치의%20설계/처리율%20제한%20알고리즘%20상세%20설계.md) 
  + 문제 2개

**Comment by gunh0** [comment]
END
